### ISSUE TITLE
damerau_levenshtein kills python kernel

### ISSUE THREAD

**Issue by funkindy** [orsinium/textdistance#11]
Python version: 3.5
textdistance version: current [extras] version from pypi (pip install textdistance[extras])

`import textdistance`
`textdistance.damerau_levenshtein("text", "test")`

Instantly leads to "Kernel died, restarting" in ipython console. Can provide any needed info.

**Comment by orsinium** [comment]
Hm. Can't reproduce:

```bash
mkvirtualenv test
pip install textdistance[extras] ipython
ipython
```
```python
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import textdistance
   ...: textdistance.damerau_levenshtein("text", "test")
   ...: 
Out[1]: 1
```

1. You're use virtualenviroment? If no, can you reproduce it in virtualenv?
2. What is your OS?
3. You're run ipython from console?

**Comment by funkindy** [comment]
Im on Windows 10, same here for clean environment. Seems more like OS issue.

**Comment by orsinium** [comment]
Please, try this snippets:

```python
import textdistance
textdistance.DamerauLevenshtein(external=False)("text", "test")
```

```python
import jellyfish
jellyfish.damerau_levenshtein_distance(u"text", u"test")
```

```python
import pyxdameraulevenshtein
pyxdameraulevenshtein.damerau_levenshtein_distance(u"text", u"test")
```

**Comment by funkindy** [comment]
Tried it. Last (pyxdameraulevenshtein) one crashes the kernel.

**Comment by orsinium** [comment]
Please, create issue into pyxDamerauLevenshtein project:
https://github.com/gfairchild/pyxDamerauLevenshtein/issues

You can use disable external libraries usage for TextDistance by passing `external=False` on class initialization:

```python3
import textdistance
damerau_levenshtein = textdistance.DamerauLevenshtein(external=False)
damerau_levenshtein("text", "test")
```

**Comment by jrcinco** [comment]
Need update the compiler for installing the extras.

**For apt (Ubuntu, Debian...):**
sudo apt-get install python-dev # for python2.x installs 
sudo apt-get install python3-dev # for python3.x installs
sudo apt-get install -y liblzma-dev

**For apt-cyg (Cygwin...):**
apt-cyg install python-devel   # for python2.x installs
apt-cyg install python3-devel  # for python3.x installs

------
pip install textdistance[extras]   # for python2.x installs
pip3 install textdistance[extras] # for python3.x installs
