### ISSUE TITLE
Choose method using variable

### ISSUE THREAD

**Issue by GildasLepennetier** [orsinium/textdistance#12]
Hi,
More idea than issue: 
It would be very useful to be able to choose the methods using a variable. Users could be able to switch methods more easily:

```
import textdistance
string1="test"
string2="text"
method="hamming.similarity"
textdistance.distance(string1, string2, method)
```

**Comment by orsinium** [comment]
Python can apply getattr to modules:
```python
getattr(textdistance, 'hamming', 'similarity')('test', 'text')
```

**Comment by GildasLepennetier** [comment]
Ho thanks. Indeed, doing exactly the job.
