### ISSUE TITLE
MLIPNS Not working

### ISSUE THREAD

**Issue by bhangaboy** [orsinium/textdistance#13]
Hi,
Just ran a test over MLIPNS. It raised following error

~/NEM-Python3/lib/python3.6/site-packages/textdistance/algorithms/base.py in similarity(self, *sequences)
    157 
    158     def similarity(self, *sequences):
--> 159         return self(*sequences)
    160 
    161     def quick_answer(self, *sequences):

TypeError: 'str' object is not callable

**Comment by orsinium** [comment]
Can't reproduce:

```python
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import textdistance

In [2]: textdistance.mlipns.similarity('test', 'text')
Out[2]: 1

In [3]: textdistance.mlipns.distance('test', 'text')
Out[3]: 0

In [4]: textdistance.mlipns('test', 'text')
Out[4]: 1
```

Please, provide steps to reproduce and full traceback.

**Comment by orsinium** [comment]
Oh, I see. Use class instance instead of class. In your case `mlipns` instead of `MLIPNS`, as in example in my previous message.

 Thank you for usage :)
