### ISSUE TITLE
The function textdistance.lcsseq has been running for a long time without returning.

### ISSUE THREAD

**Issue by WingCHWang** [orsinium/textdistance#15]
I am running the following code using textdistance 3.0.3 under Python 3.6: 
<pre><code>import textdistance
print(textdistance.lcsseq("random exponential", "layer activation"))</code></pre>
This code has not returned for a long time, is it caught in an infinite loop?

**Comment by orsinium** [comment]
Wow. Thank you. This is infinite recursion. I use recursive realization here. I will debug it.

**Comment by orsinium** [comment]
Thank you for report again! I've fixed it. This issue depends on the very bad performance of recursion based realization. So, I've added dynamic programming based realization that used in `lcsseq` when you pass only 2 sequences. For 3 or more sequences (for example, `lcsseq('test', 'text', 'tempit')`) recursive realization will be used.

Please, update project version:

```
pip install -U --no-cache-dir textdistance
```

Feel free to give any feedback :)
