### ISSUE TITLE
Unable to use due in PySpark on AWS

### ISSUE THREAD

**Issue by ericandrewmeadows** [orsinium/textdistance#17]
I am attempting to use this lib in AWS, and it is a simple change - extracting the zip path to the json.  For context, AWS Glue Jobs use PySpark, and libraries are only importable as `.zip` or singular `.py` files, and textdistance fails to open the `libraries.json` file because it is housed in the zip file.

**Comment by ericandrewmeadows** [comment]
```from requests.utils import extract_zipped_paths


CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
LIBRARIES_FILE = os.path.join(CURRENT_DIR, 'libraries.json')
if '.zip' in CURRENT_DIR:
	LIBRARIES_FILE = extract_zipped_paths(LIBRARIES_FILE)``` will fix the issue, but I don't have repo access.

**Comment by orsinium** [comment]
I'm not sure that it's related to the library code, I guess. You would have the same issues with any other library with static files as well. How do other libs solve this? For example, Django has many built-in templates and do the same thing that textdistance.

**Comment by orsinium** [comment]
Yeah, [docs recommend to use egg](https://www.cloudera.com/documentation/enterprise/5-7-x/topics/spark_python.html#spark_python__section_b2q_pzs_b5) for this case. Check it, please.
