### ISSUE TITLE
Incorrect values for Sorensen-Dice coefficient

### ISSUE THREAD

**Issue by kinow** [orsinium/textdistance#18]
Hi,

I am looking at the output values for the Sorensen-Dice coefficient to compare with a [new implementation for Java](https://issues.apache.org/jira/browse/TEXT-126).

I just installed the library in an environment with Ubuntu LTS, Anaconda Py 3.6, via `pip install textdistance`. Then tried the example [from the Wikipedia page](https://en.wikipedia.org/wiki/S%C3%B8rensen%E2%80%93Dice_coefficient), where `f('night', 'nacth') = 0.25`, with bigrams.

Haven't looked at the Python code yet, but is there any parameter that I must use to get the same value from the Wikipedia page? Here's what I tried in the console.

```bash
Python 3.7.2 (default, Dec 29 2018, 06:19:36) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import textdistance
>>> textdistance.sorensen
<textdistance.algorithms.token_based.Sorensen object at 0x7f6c702d6f98>
>>> textdistance.sorensen("night", "nacht")
0.6
>>> textdistance.sorensen_dice("night", "nacht")
0.6
>>> textdistance.__version__
'3.0.2'
```

Cheers
Bruno

**Comment by orsinium** [comment]
Thank you for your issue. On the wiki, the example uses comparing words as bigrams. You can set up the size of q-grams via `qval` argument:

```python
textdistance.Sorensen(qval=2)("night", "nacht")
# 0.25
```

Some possible questions:

> Why `qval=1` by default?

One of the goals of TextDistance is to provide a universal interface for all algorithms. So, all algorithms have to have the same default value for the same parameter.

> Why all parameters passed only in classes, not in the functions?

This is for compatibility with Python 2. Most of the functions can get more than 2 sequences as arguments, but Python 2 doesn't support any arguments (except `**kwargs`) after `*args`.

I hope, textdistance really works for you :)

**Comment by kinow** [comment]
Thanks for the quick and really detailed answer!
