### ISSUE TITLE
gotoh normalized_similarity gives negative value

### ISSUE THREAD

**Issue by HAD1M** [orsinium/textdistance#30]
I try using gotoh.normalized_similarity('Jakarta', 'xxx') but it gives negative value

**Comment by HAD1M** [comment]
I think the problem is with this part of code
```
   def maximum(self, *sequences):
        return min(map(len, sequences))
```
shoudln't it be max not min ?

**Comment by HAD1M** [comment]
By the way, I found that needleman_wunsch.normalized_similarity('xxx', 'xxxxxxxxxxx') gives negative value too

**Comment by orsinium** [comment]
Yeah, gotoh is a variation of needleman wunsch. I will fix them both, thank you :)

**Comment by orsinium** [comment]
This is because Needleman and Gotoh similarities return negative values.
