### ISSUE TITLE
ZeroDivisionError: float division by zero 

### ISSUE THREAD

**Issue by belerico** [orsinium/textdistance#31]
The error is returned when comparing two empty string.
`line 42, in normalized_distance
    return float(self.distance(*sequences)) / self.maximum(*sequences)`

**Comment by orsinium** [comment]
Yeah, my favorite exception!

Please, provide steps to reproduce.

**Comment by belerico** [comment]
```
import textdistance
textdistance.Levenshtein().normalized_similarity('', '')
line 42, in normalized_distance
    return float(self.distance(*sequences)) / self.maximum(*sequences)
ZeroDivisionError: float division by zero
```
I'm using Python 3.7.3
Sorry for my delayed answer @orsinium

**Comment by orsinium** [comment]
Thank you, I'll have a look at it :)
