### ISSUE TITLE
Cannot import sequence based classes

### ISSUE THREAD

**Issue by svetlana21** [orsinium/textdistance#4]
Hello!
Thank you for your library, it's beneficial and easy to use.
I encountered a problem while trying to import LCSSeq class. Then I understood that I cannot import the LCSStr and RatcliffObershelp classes. It seems they are the only classes which don't work with the class interface.
![default](https://user-images.githubusercontent.com/21115815/38020210-d3918f00-32a3-11e8-89e8-817dece856d8.png)

**Comment by orsinium** [comment]
Fixed! Please, update textdistance to version 2.0.3. And thank you for response :)

**Comment by svetlana21** [comment]
Thank you!
