### ISSUE TITLE
Does rle_ncd always return 1.0?

### ISSUE THREAD

**Issue by svetlana21** [orsinium/textdistance#5]
Hello!
I'm not sure if this is a bug, but it seems that rle_ncd works incorrectly. It always returns 1.0. When I try to compare two completely different strings and two completely same ones all metrics change their values except rle_ncd.

**Comment by snjv94** [comment]
textdistance.hamming.normalized_distance('test', 'text') returning 0 and textdistance.hamming.normalized_similarity('test', 'text') returning 1

**Comment by orsinium** [comment]
Yeah, it's not bug.

## RLE (run-length encoding)

This is simple compression method, but worst for distance analyse.

```python
>>> from textdistance.algorithms.compression_based import NCD, rle_ncd
>>> NCD()._rle('qwe')
'qwe'
>>> NCD()._rle('qwee')
'qwee'
>>> NCD()._rle('qweee')
'qw3e'
>>> NCD()._rle('qweeee')
'qw4e'
>>> NCD()._rle('qweqwe')
'qweqwe'
```

# NCD

`NCD(A, B) = [len(Z(A + B)) - min(len(Z(A)), len(Z(B)))] / max(len(Z(A)), len(Z(B)))`

```python
>>> len(NCD()._rle('qweqwe'))
6
>>> len(NCD()._rle('qwe'))
3
>>> assert rle_ncd('qwe', 'qwe') == (6 - 3) / 3 == 1
```

```python
>>> len(NCD()._rle('t' * 3))
2
>>> len(NCD()._rle('t' * 6))
2
>>> assert rle_ncd('ttt', 'ttt') == (2 - 2) / 2 == 0
```

NCD by RLE only indicate prefix and postfix equality:

```python
>>> NCD()._rle('attt')
'a3t'
>>> NCD()._rle('ttta')
'3ta'
>>> NCD()._rle('attt' + 'ttta')
'a6ta'
>>> assert rle_ncd('attt', 'ttta') == (4. - 3) / 3 == 1. / 3
```

**Comment by orsinium** [comment]
@snjv94, this is bug, thank you for report. In python2 division int to int return int, not float. I fix it. Please, update textdistance to version 3.0.3.
