### ISSUE TITLE
Mistake while using arith_ncd

### ISSUE THREAD

**Issue by svetlana21** [orsinium/textdistance#6]
Another mistake I encountered:
![default](https://user-images.githubusercontent.com/21115815/38070212-00904978-3345-11e8-830d-0ddbdb5702a3.png)
P.S.: I remember that compression part of your library is in progress, but prefer to point out these mistakes, may be my remarks will be useful

**Comment by orsinium** [comment]
Yeah, compression based algos in progress. I do not recommend use any these algos. Thank you for response. I notofy you when this part will be stable :)

**Comment by svetlana21** [comment]
OK, thank you! I'm looking forward for these metrics

**Comment by orsinium** [comment]
1. Now `arith_ncd` works.
2. NCD for any algorithms gives strange results because all real compression algorithms aren't "normal compressors". I'm thinking about implementing it, but this is not so trivial :)
