### ISSUE TITLE
Time of Levenshtein distance calculation

### ISSUE THREAD

**Issue by svetlana21** [orsinium/textdistance#7]
Sorry, but it looks like problem again. I tried to calculate levenshtein distance. I waited around 40 minutes but nothing happened.

**Comment by orsinium** [comment]
Yeah, I know about this problem. Work in progress in this branch:
https://github.com/orsinium/textdistance/tree/optional-dependencies
This release will be use optional dependencies, like Jellifish, and Damerau-Levenstein will be very fast, I promise :)

Remains to implement:
- Right algorithm selecting
- Moooore tests. Some tests [already done](https://github.com/orsinium/textdistance/blob/optional-dependencies/tests/external.py), and all works fine.

If you urgently want this feature, you can temporally use project from this branch:
```bash
pip install -e git+https://github.com/orsinium/textdistance.git@optional-dependencies#egg=textdistance
```

**Comment by orsinium** [comment]
I plan released it asap. Please be patient :)

**Comment by svetlana21** [comment]
look forward for it :)

**Comment by orsinium** [comment]
It's released! And also TextDistance's native Levenshtein realization so many faster :)
